apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quickwit-cert
  namespace: quickwit
spec:
  secretName: quickwit-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: quickwit.onionstreasure.com
  dnsNames:
    - quickwit.onionstreasure.com
