# quickwit-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quickwit-pvc
  namespace: quickwit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
